@echo off
<<<<<<< HEAD
echo Starting Unified Ticketing ^& Attendance System...
=======
echo Starting Unified Ticketing & Attendance System...
>>>>>>> 8ab38add65cb6c2995cfc83dfbfa5d793287fa4f

echo Starting Backend (Port 5000)...
start "Unified Backend" /D "backend" nodemon server.js

echo Starting Frontend (Port 5173)...
start "Unified Frontend" npm run dev

echo Application starting...
